# Generated by Django 5.2 on 2025-04-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ip', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_executed', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Datapoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_collected', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('capacitive', models.FloatField()),
                ('sensor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.sensor_request')),
            ],
        ),
    ]
